name: VyOS v1.3 LTS

on:
  workflow_dispatch:

env:
  BUILD_ARCH: amd64
  BUILD_BY: ian@ianhattendorf.com
  BUILD_TYPE: release
  GIT_CLONE_URL: https://github.com/vyos/vyos-build

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    container:
      image: vyos/vyos-build:equuleus
      options: --workdir /vyos --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone vyos-build
        run: |
          set -eux
          mkdir artifacts
          git clone -b equuleus --single-branch "$GIT_CLONE_URL" vyos-build
          cd vyos-build
          printf 'untrusted comment: minisign public key 4D5CB06C59D8EDCB\nRWTL7dhZbLBcTbB00noWgABYO51hl2SBPn2twoK3Hn9DXLSIwT3d3XWs\n' > data/live-build-config/includes.chroot/usr/share/vyos/keys/vyos-release.minisign.pub
          export VYOS_VERSION="1.3.$(date "+%Y%m%d")-$(git rev-parse --short HEAD)"
          echo "Building VyOS v$VYOS_VERSION..."
          echo "VYOS_VERSION=$VYOS_VERSION" >> "$GITHUB_ENV"
          ./configure --architecture "$BUILD_ARCH" --build-by "$BUILD_BY" --build-type "$BUILD_TYPE" --version "$VYOS_VERSION"

      - name: Build ISO
        working-directory: ./vyos-build
        run: |
          set -eux
          make iso
          cp "./build/vyos-$VYOS_VERSION-$BUILD_ARCH.iso" ../artifacts/

      - name: Sign ISO
        env:
          MINISIGN_SECRET_KEY: ${{ secrets.MINISIGN_SECRET_KEY }}
          MINISIGN_SECRET_KEY_PASSPHRASE: ${{ secrets.MINISIGN_SECRET_KEY_PASSPHRASE }}
        run: |
          set -eux
          wget https://github.com/jedisct1/minisign/releases/download/0.11/minisign-0.11-linux.tar.gz
          printf 'f0a0954413df8531befed169e447a66da6868d79052ed7e892e50a4291af7ae0  minisign-0.11-linux.tar.gz\n' > minisign-0.11-linux.tar.gz.sha256
          sha256sum -c minisign-0.11-linux.tar.gz.sha256 || exit 1
          tar xf minisign-0.11-linux.tar.gz
          printf "%s\n" "$MINISIGN_SECRET_KEY" > ./minisign.key
          printf "%s\n" "$MINISIGN_SECRET_KEY_PASSPHRASE" | ./minisign-linux/x86_64/minisign -S -s ./minisign.key -m "artifacts/vyos-${{ env.VYOS_VERSION }}-${{ env.BUILD_ARCH }}.iso"

      - uses: ncipollo/release-action@v1
        with:
          artifacts: artifacts/vyos-${{ env.VYOS_VERSION }}-${{ env.BUILD_ARCH }}.*
          body: VyOS v${{ env.VYOS_VERSION }} LTS
          name: VyOS v${{ env.VYOS_VERSION }} LTS
          commit: ${{ github.sha }}
          tag: ${{ env.VYOS_VERSION }}
